[2025-09-04T13:07:48.651+0545] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-09-04T13:07:48.658+0545] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: diabetes_pipeline_setup.start_mlflow manual__2025-09-04T07:22:42.313835+00:00 [queued]>
[2025-09-04T13:07:48.661+0545] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: diabetes_pipeline_setup.start_mlflow manual__2025-09-04T07:22:42.313835+00:00 [queued]>
[2025-09-04T13:07:48.661+0545] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-09-04T13:07:48.674+0545] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): start_mlflow> on 2025-09-04 07:22:42.313835+00:00
[2025-09-04T13:07:48.678+0545] {standard_task_runner.py:72} INFO - Started process 93955 to run task
[2025-09-04T13:07:48.681+0545] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'diabetes_pipeline_setup', 'start_mlflow', 'manual__2025-09-04T07:22:42.313835+00:00', '--job-id', '95', '--raw', '--subdir', 'DAGS_FOLDER/bash_operator.py', '--cfg-path', '/tmp/tmpc4574xf8']
[2025-09-04T13:07:48.681+0545] {standard_task_runner.py:105} INFO - Job 95: Subtask start_mlflow
[2025-09-04T13:07:48.707+0545] {task_command.py:467} INFO - Running <TaskInstance: diabetes_pipeline_setup.start_mlflow manual__2025-09-04T07:22:42.313835+00:00 [running]> on host ashok-Nitro-ANV16-41
[2025-09-04T13:07:48.746+0545] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='diabetes_pipeline_setup' AIRFLOW_CTX_TASK_ID='start_mlflow' AIRFLOW_CTX_EXECUTION_DATE='2025-09-04T07:22:42.313835+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-04T07:22:42.313835+00:00'
[2025-09-04T13:07:48.747+0545] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-09-04T13:07:48.747+0545] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-09-04T13:07:48.747+0545] {logging_mixin.py:190} INFO - Current task name:start_mlflow state:running start_date:2025-09-04 07:22:48.658392+00:00
[2025-09-04T13:07:48.747+0545] {logging_mixin.py:190} INFO - Dag name:diabetes_pipeline_setup and current dag run status:running
[2025-09-04T13:07:48.747+0545] {taskinstance.py:732} INFO - ::endgroup::
[2025-09-04T13:07:48.748+0545] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-09-04T13:07:48.748+0545] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'source ~/miniconda3/etc/profile.d/conda.sh && conda activate mysecondenvironment && mlflow server --backend-store-uri sqlite:///mlflow.db --default-artifact-root ./mlruns --host 0.0.0.0 --port 5000']
[2025-09-04T13:07:48.758+0545] {subprocess.py:99} INFO - Output:
[2025-09-04T13:07:49.688+0545] {subprocess.py:106} INFO - 2025/09/04 13:07:49 INFO mlflow.store.db.utils: Creating initial MLflow database tables...
[2025-09-04T13:07:49.721+0545] {subprocess.py:106} INFO - 2025/09/04 13:07:49 INFO mlflow.store.db.utils: Updating database tables
[2025-09-04T13:07:49.724+0545] {subprocess.py:106} INFO - INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
[2025-09-04T13:07:49.725+0545] {subprocess.py:106} INFO - INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
[2025-09-04T13:07:49.749+0545] {subprocess.py:106} INFO - INFO  [alembic.runtime.migration] Running upgrade  -> 451aebb31d03, add metric step
[2025-09-04T13:07:49.777+0545] {subprocess.py:106} INFO - INFO  [alembic.runtime.migration] Running upgrade 451aebb31d03 -> 90e64c465722, migrate user column to tags
[2025-09-04T13:07:49.788+0545] {subprocess.py:106} INFO - INFO  [alembic.runtime.migration] Running upgrade 90e64c465722 -> 181f10493468, allow nulls for metric values
[2025-09-04T13:07:49.806+0545] {subprocess.py:106} INFO - INFO  [alembic.runtime.migration] Running upgrade 181f10493468 -> df50e92ffc5e, Add Experiment Tags Table
[2025-09-04T13:07:49.821+0545] {subprocess.py:106} INFO - INFO  [alembic.runtime.migration] Running upgrade df50e92ffc5e -> 7ac759974ad8, Update run tags with larger limit
[2025-09-04T13:07:49.839+0545] {subprocess.py:106} INFO - INFO  [alembic.runtime.migration] Running upgrade 7ac759974ad8 -> 89d4b8295536, create latest metrics table
[2025-09-04T13:07:49.852+0545] {subprocess.py:106} INFO - INFO  [89d4b8295536_create_latest_metrics_table_py] Migration complete!
[2025-09-04T13:07:49.859+0545] {subprocess.py:106} INFO - INFO  [alembic.runtime.migration] Running upgrade 89d4b8295536 -> 2b4d017a5e9b, add model registry tables to db
[2025-09-04T13:07:49.860+0545] {subprocess.py:106} INFO - INFO  [2b4d017a5e9b_add_model_registry_tables_to_db_py] Adding registered_models and model_versions tables to database.
[2025-09-04T13:07:49.874+0545] {subprocess.py:106} INFO - INFO  [2b4d017a5e9b_add_model_registry_tables_to_db_py] Migration complete!
[2025-09-04T13:07:49.881+0545] {subprocess.py:106} INFO - INFO  [alembic.runtime.migration] Running upgrade 2b4d017a5e9b -> cfd24bdc0731, Update run status constraint with killed
[2025-09-04T13:07:49.903+0545] {subprocess.py:106} INFO - INFO  [alembic.runtime.migration] Running upgrade cfd24bdc0731 -> 0a8213491aaa, drop_duplicate_killed_constraint
[2025-09-04T13:07:49.912+0545] {subprocess.py:106} INFO - INFO  [alembic.runtime.migration] Running upgrade 0a8213491aaa -> 728d730b5ebd, add registered model tags table
[2025-09-04T13:07:49.927+0545] {subprocess.py:106} INFO - INFO  [alembic.runtime.migration] Running upgrade 728d730b5ebd -> 27a6a02d2cf1, add model version tags table
[2025-09-04T13:07:49.941+0545] {subprocess.py:106} INFO - INFO  [alembic.runtime.migration] Running upgrade 27a6a02d2cf1 -> 84291f40a231, add run_link to model_version
[2025-09-04T13:07:49.955+0545] {subprocess.py:106} INFO - INFO  [alembic.runtime.migration] Running upgrade 84291f40a231 -> a8c4a736bde6, allow nulls for run_id
[2025-09-04T13:07:49.973+0545] {subprocess.py:106} INFO - INFO  [alembic.runtime.migration] Running upgrade a8c4a736bde6 -> 39d1c3be5f05, add_is_nan_constraint_for_metrics_tables_if_necessary
[2025-09-04T13:07:49.998+0545] {subprocess.py:106} INFO - INFO  [alembic.runtime.migration] Running upgrade 39d1c3be5f05 -> c48cb773bb87, reset_default_value_for_is_nan_in_metrics_table_for_mysql
[2025-09-04T13:07:50.005+0545] {subprocess.py:106} INFO - INFO  [alembic.runtime.migration] Running upgrade c48cb773bb87 -> bd07f7e963c5, create index on run_uuid
[2025-09-04T13:07:50.040+0545] {subprocess.py:106} INFO - INFO  [alembic.runtime.migration] Running upgrade bd07f7e963c5 -> 0c779009ac13, add deleted_time field to runs table
[2025-09-04T13:07:50.054+0545] {subprocess.py:106} INFO - INFO  [alembic.runtime.migration] Running upgrade 0c779009ac13 -> cc1f77228345, change param value length to 500
[2025-09-04T13:07:50.075+0545] {subprocess.py:106} INFO - INFO  [alembic.runtime.migration] Running upgrade cc1f77228345 -> 97727af70f4d, Add creation_time and last_update_time to experiments table
[2025-09-04T13:07:50.096+0545] {subprocess.py:106} INFO - INFO  [alembic.runtime.migration] Running upgrade 97727af70f4d -> 3500859a5d39, Add Model Aliases table
[2025-09-04T13:07:50.110+0545] {subprocess.py:106} INFO - INFO  [alembic.runtime.migration] Running upgrade 3500859a5d39 -> 7f2a7d5fae7d, add datasets inputs input_tags tables
[2025-09-04T13:07:50.170+0545] {subprocess.py:106} INFO - INFO  [alembic.runtime.migration] Running upgrade 7f2a7d5fae7d -> 2d6e25af4d3e, increase max param val length from 500 to 8000
[2025-09-04T13:07:50.190+0545] {subprocess.py:106} INFO - INFO  [alembic.runtime.migration] Running upgrade 2d6e25af4d3e -> acf3f17fdcc7, add storage location field to model versions
[2025-09-04T13:07:50.202+0545] {subprocess.py:106} INFO - INFO  [alembic.runtime.migration] Running upgrade acf3f17fdcc7 -> 867495a8f9d4, add trace tables
[2025-09-04T13:07:50.248+0545] {subprocess.py:106} INFO - INFO  [alembic.runtime.migration] Running upgrade 867495a8f9d4 -> 5b0e9adcef9c, add cascade deletion to trace tables foreign keys
[2025-09-04T13:07:50.274+0545] {subprocess.py:106} INFO - INFO  [alembic.runtime.migration] Running upgrade 5b0e9adcef9c -> 4465047574b1, increase max dataset schema size
[2025-09-04T13:07:50.281+0545] {subprocess.py:106} INFO - INFO  [alembic.runtime.migration] Running upgrade 4465047574b1 -> f5a4f2784254, increase run tag value limit to 8000
[2025-09-04T13:07:50.306+0545] {subprocess.py:106} INFO - INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
[2025-09-04T13:07:50.307+0545] {subprocess.py:106} INFO - INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
[2025-09-04T13:07:50.383+0545] {subprocess.py:106} INFO - [2025-09-04 13:07:50 +0545] [94000] [INFO] Starting gunicorn 23.0.0
[2025-09-04T13:07:50.384+0545] {subprocess.py:106} INFO - [2025-09-04 13:07:50 +0545] [94000] [INFO] Listening at: http://0.0.0.0:5000 (94000)
[2025-09-04T13:07:50.384+0545] {subprocess.py:106} INFO - [2025-09-04 13:07:50 +0545] [94000] [INFO] Using worker: sync
[2025-09-04T13:07:50.386+0545] {subprocess.py:106} INFO - [2025-09-04 13:07:50 +0545] [94002] [INFO] Booting worker with pid: 94002
[2025-09-04T13:07:50.473+0545] {subprocess.py:106} INFO - [2025-09-04 13:07:50 +0545] [94003] [INFO] Booting worker with pid: 94003
[2025-09-04T13:07:50.507+0545] {subprocess.py:106} INFO - [2025-09-04 13:07:50 +0545] [94004] [INFO] Booting worker with pid: 94004
[2025-09-04T13:07:50.589+0545] {subprocess.py:106} INFO - [2025-09-04 13:07:50 +0545] [94006] [INFO] Booting worker with pid: 94006
[2025-09-04T13:13:16.503+0545] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-09-04T13:13:16.512+0545] {process_utils.py:132} INFO - Sending 15 to group 93955. PIDs of all processes in the group: [93958, 94000, 94002, 94003, 94004, 94006, 93955]
[2025-09-04T13:13:16.513+0545] {process_utils.py:87} INFO - Sending the signal 15 to group 93955
[2025-09-04T13:13:16.513+0545] {taskinstance.py:3094} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-09-04T13:13:16.516+0545] {taskinstance.py:3095} ERROR - Stacktrace: 
  File "/home/ashok/miniconda3/envs/mysecondenvironment/bin/airflow", line 8, in <module>
    sys.exit(main())
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/__main__.py", line 62, in main
    args.func(args)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 254, in _run_task_by_selected_method
    return _run_task_by_local_task_job(args, ti)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 322, in _run_task_by_local_task_job
    ret = run_job(job=job_runner.job, execute_callable=job_runner._execute)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/jobs/job.py", line 421, in run_job
    return execute_job(job, execute_callable=execute_callable)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/jobs/job.py", line 450, in execute_job
    ret = execute_callable()
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/jobs/local_task_job_runner.py", line 171, in _execute
    self.task_runner.start()
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/task/task_runner/standard_task_runner.py", line 55, in start
    self.process = self._start_by_fork()
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/operators/bash.py", line 257, in execute
    result = self._run_inline_command(bash_path=bash_path, env=env)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/operators/bash.py", line 284, in _run_inline_command
    return self.subprocess_hook.run_command(
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/hooks/subprocess.py", line 104, in run_command
    for raw_line in iter(self.sub_process.stdout.readline, b""):
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 3095, in signal_handler
    self.log.error("Stacktrace: \n%s", "".join(traceback.format_stack()))

[2025-09-04T13:13:16.516+0545] {subprocess.py:117} INFO - Sending SIGTERM signal to process group
[2025-09-04T13:13:16.520+0545] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/operators/bash.py", line 257, in execute
    result = self._run_inline_command(bash_path=bash_path, env=env)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/operators/bash.py", line 284, in _run_inline_command
    return self.subprocess_hook.run_command(
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/hooks/subprocess.py", line 104, in run_command
    for raw_line in iter(self.sub_process.stdout.readline, b""):
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 3097, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2025-09-04T13:13:16.524+0545] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-09-04T13:13:16.524+0545] {logging_mixin.py:190} INFO - Task start:2025-09-04 07:22:48.658392+00:00 end:2025-09-04 07:28:16.524061+00:00 duration:327.865669
[2025-09-04T13:13:16.524+0545] {logging_mixin.py:190} INFO - Task:<Task(BashOperator): start_mlflow> dag:<DAG: diabetes_pipeline_setup> dagrun:<DagRun diabetes_pipeline_setup @ 2025-09-04 07:22:42.313835+00:00: manual__2025-09-04T07:22:42.313835+00:00, state:running, queued_at: 2025-09-04 07:22:42.321914+00:00. externally triggered: True>
[2025-09-04T13:13:16.524+0545] {logging_mixin.py:190} INFO - Failure caused by Task received SIGTERM signal
[2025-09-04T13:13:16.524+0545] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=diabetes_pipeline_setup, task_id=start_mlflow, run_id=manual__2025-09-04T07:22:42.313835+00:00, execution_date=20250904T072242, start_date=20250904T072248, end_date=20250904T072816
[2025-09-04T13:13:16.549+0545] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-09-04T13:13:16.565+0545] {process_utils.py:80} INFO - Process psutil.Process(pid=93958, status='terminated', started='13:07:48') (93958) terminated with exit code None
[2025-09-04T13:13:16.565+0545] {process_utils.py:80} INFO - Process psutil.Process(pid=93955, status='terminated', exitcode=2, started='13:07:47') (93955) terminated with exit code 2
[2025-09-04T13:13:16.565+0545] {process_utils.py:80} INFO - Process psutil.Process(pid=94006, status='terminated', started='13:07:49') (94006) terminated with exit code None
[2025-09-04T13:13:16.565+0545] {process_utils.py:80} INFO - Process psutil.Process(pid=94002, status='terminated', started='13:07:49') (94002) terminated with exit code None
[2025-09-04T13:13:16.565+0545] {process_utils.py:80} INFO - Process psutil.Process(pid=94003, status='terminated', started='13:07:49') (94003) terminated with exit code None
[2025-09-04T13:13:16.566+0545] {process_utils.py:80} INFO - Process psutil.Process(pid=94004, status='terminated', started='13:07:49') (94004) terminated with exit code None
[2025-09-04T13:13:16.658+0545] {process_utils.py:80} INFO - Process psutil.Process(pid=94000, status='terminated', started='13:07:49') (94000) terminated with exit code None
[2025-09-04T13:13:18.765+0545] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-09-04T13:13:18.774+0545] {taskinstance.py:2604} INFO - Dependencies not met for <TaskInstance: diabetes_pipeline_setup.start_mlflow manual__2025-09-04T07:22:42.313835+00:00 [up_for_retry]>, dependency 'Not In Retry Period' FAILED: Task is not ready for retry yet but will be retried automatically. Current date is 2025-09-04T07:28:18.774719+00:00 and task will be retried at 2025-09-04T07:33:16.524061+00:00.
[2025-09-04T13:13:18.775+0545] {local_task_job_runner.py:166} INFO - Task is not able to be run
