[2025-09-04T17:40:15.136+0545] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-09-04T17:40:15.142+0545] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: start_diabetes_stack.start_mlflow manual__2025-09-04T11:55:05.093019+00:00 [queued]>
[2025-09-04T17:40:15.145+0545] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: start_diabetes_stack.start_mlflow manual__2025-09-04T11:55:05.093019+00:00 [queued]>
[2025-09-04T17:40:15.145+0545] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-09-04T17:40:15.158+0545] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): start_mlflow> on 2025-09-04 11:55:05.093019+00:00
[2025-09-04T17:40:15.163+0545] {standard_task_runner.py:72} INFO - Started process 128751 to run task
[2025-09-04T17:40:15.165+0545] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'start_diabetes_stack', 'start_mlflow', 'manual__2025-09-04T11:55:05.093019+00:00', '--job-id', '254', '--raw', '--subdir', 'DAGS_FOLDER/bash_operator.py', '--cfg-path', '/tmp/tmpouzkemp3']
[2025-09-04T17:40:15.166+0545] {standard_task_runner.py:105} INFO - Job 254: Subtask start_mlflow
[2025-09-04T17:40:15.191+0545] {task_command.py:467} INFO - Running <TaskInstance: start_diabetes_stack.start_mlflow manual__2025-09-04T11:55:05.093019+00:00 [running]> on host ashok-Nitro-ANV16-41
[2025-09-04T17:40:15.230+0545] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ashok' AIRFLOW_CTX_DAG_ID='start_diabetes_stack' AIRFLOW_CTX_TASK_ID='start_mlflow' AIRFLOW_CTX_EXECUTION_DATE='2025-09-04T11:55:05.093019+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-04T11:55:05.093019+00:00'
[2025-09-04T17:40:15.230+0545] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-09-04T17:40:15.231+0545] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-09-04T17:40:15.231+0545] {logging_mixin.py:190} INFO - Current task name:start_mlflow state:running start_date:2025-09-04 11:55:15.143078+00:00
[2025-09-04T17:40:15.231+0545] {logging_mixin.py:190} INFO - Dag name:start_diabetes_stack and current dag run status:running
[2025-09-04T17:40:15.231+0545] {taskinstance.py:732} INFO - ::endgroup::
[2025-09-04T17:40:15.231+0545] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-09-04T17:40:15.231+0545] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', '\n        source ~/anaconda3/etc/profile.d/conda.sh\n        conda activate mysecondenvironment\n        nohup mlflow ui --host 0.0.0.0 --port 5000 > ~/mlflow.log 2>&1 &\n        ']
[2025-09-04T17:40:15.242+0545] {subprocess.py:99} INFO - Output:
[2025-09-04T17:40:15.243+0545] {subprocess.py:106} INFO - /usr/bin/bash: line 2: /home/ashok/anaconda3/etc/profile.d/conda.sh: No such file or directory
[2025-09-04T17:40:15.334+0545] {subprocess.py:106} INFO - 
[2025-09-04T17:40:15.334+0545] {subprocess.py:106} INFO - CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
[2025-09-04T17:40:15.334+0545] {subprocess.py:106} INFO - To initialize your shell, run
[2025-09-04T17:40:15.334+0545] {subprocess.py:106} INFO - 
[2025-09-04T17:40:15.334+0545] {subprocess.py:106} INFO -     $ conda init <SHELL_NAME>
[2025-09-04T17:40:15.334+0545] {subprocess.py:106} INFO - 
[2025-09-04T17:40:15.335+0545] {subprocess.py:106} INFO - Currently supported shells are:
[2025-09-04T17:40:15.335+0545] {subprocess.py:106} INFO -   - bash
[2025-09-04T17:40:15.335+0545] {subprocess.py:106} INFO -   - fish
[2025-09-04T17:40:15.335+0545] {subprocess.py:106} INFO -   - tcsh
[2025-09-04T17:40:15.335+0545] {subprocess.py:106} INFO -   - xonsh
[2025-09-04T17:40:15.335+0545] {subprocess.py:106} INFO -   - zsh
[2025-09-04T17:40:15.335+0545] {subprocess.py:106} INFO -   - powershell
[2025-09-04T17:40:15.335+0545] {subprocess.py:106} INFO - 
[2025-09-04T17:40:15.335+0545] {subprocess.py:106} INFO - See 'conda init --help' for more information and options.
[2025-09-04T17:40:15.335+0545] {subprocess.py:106} INFO - 
[2025-09-04T17:40:15.335+0545] {subprocess.py:106} INFO - IMPORTANT: You may need to close and restart your shell after running 'conda init'.
[2025-09-04T17:40:15.335+0545] {subprocess.py:106} INFO - 
[2025-09-04T17:40:15.335+0545] {subprocess.py:106} INFO - 
[2025-09-04T17:40:15.351+0545] {subprocess.py:110} INFO - Command exited with return code 0
[2025-09-04T17:40:15.368+0545] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-09-04T17:40:15.368+0545] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=start_diabetes_stack, task_id=start_mlflow, run_id=manual__2025-09-04T11:55:05.093019+00:00, execution_date=20250904T115505, start_date=20250904T115515, end_date=20250904T115515
[2025-09-04T17:40:15.387+0545] {logging_mixin.py:190} INFO - Task instance in success state
[2025-09-04T17:40:15.387+0545] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-09-04T17:40:15.387+0545] {logging_mixin.py:190} INFO - Dag name:start_diabetes_stack queued_at:2025-09-04 11:55:05.100900+00:00
[2025-09-04T17:40:15.387+0545] {logging_mixin.py:190} INFO - Task hostname:ashok-Nitro-ANV16-41 operator:BashOperator
[2025-09-04T17:40:15.417+0545] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-09-04T17:40:15.425+0545] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-04T17:40:15.425+0545] {local_task_job_runner.py:245} INFO - ::endgroup::
